### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by journeym** [RocketChat/Apps.ClamAV#3]
Latest rocketchat deployed using snap, addon shows error in the logs section, stating that eicar file has virus, though file still uploads fine and can be dowloaded

**Comment by journeym** [comment]
![image](https://user-images.githubusercontent.com/7759734/197775311-10b434c3-6056-49cc-9b80-089ec0a7085d.png)
![image](https://user-images.githubusercontent.com/7759734/197775460-8b1c7bee-3627-4874-ab5e-6edfe0e56fbd.png)

**Comment by alexkorotysh** [comment]
The same story

**Comment by alexkorotysh** [comment]
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/15368568/217555062-7dd5f877-3461-4f81-8021-d16aca6f4a60.png">
<img width="913" alt="image" src="https://user-images.githubusercontent.com/15368568/217555253-f0a8d669-6e33-45bc-9f66-78a99154cc1c.png">

**Comment by d-gubert** [comment]
This issue has been solved by this PR https://github.com/RocketChat/Rocket.Chat/pull/28450

Released version 6.2.0

Thanks for the report
